package com.photos.amy.albrecht.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import com.photos.amy.albrecht.entities.Comment;
import com.photos.amy.albrecht.repo.CommentRepository;

@Service
public class CommentServices {
	private CommentRepository commentRepository;
	
	@Autowired
	public CommentServices(CommentRepository commentRepository) {
		this.commentRepository = commentRepository;
	}
	
	public void saveComment(Comment comment) {
		commentRepository.save(comment);
	}
	
	public Comment findCommentByCommentText(String commentText) {
		return commentRepository.findCommentByCommentText(commentText);
	}
	
	public Comment countByCommentId(Integer commentId) {
		return commentRepository.countByCommentId(commentId);
	}
	
	//autogenerated by Eclipse
	
	public List<Comment> findAll() {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Comment> findAll(Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Comment> findAllById(Iterable<Integer> ids) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Comment> List<S> saveAll(Iterable<S> entities) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void flush() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Comment> S saveAndFlush(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void deleteInBatch(Iterable<Comment> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAllInBatch() {
		// TODO Auto-generated method stub
		
	}

	
	public Comment getOne(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Comment> List<S> findAll(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Comment> List<S> findAll(Example<S> example, Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Page<Comment> findAll(Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Comment> S save(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Optional<Comment> findById(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public boolean existsById(Integer id) {
		// TODO Auto-generated method stub
		return false;
	}

	
	public long count() {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public void deleteById(Integer id) {
		// TODO Auto-generated method stub
		
	}

	
	public void delete(Comment entity) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll(Iterable<? extends Comment> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Comment> Optional<S> findOne(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Comment> Page<S> findAll(Example<S> example, Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Comment> long count(Example<S> example) {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public <S extends Comment> boolean exists(Example<S> example) {
		// TODO Auto-generated method stub
		return false;
	}

	
	public Comment getCommentByCommentId(int id) {
		// TODO Auto-generated method stub
		return null;
	}

}
