package com.Photos.amy.albrecht.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;


import com.Photos.amy.albrecht.models.Album;
import com.Photos.amy.albrecht.models.Photo;
import com.Photos.amy.albrecht.repo.AlbumRepository;

@Service
public class AlbumServices {
	private AlbumRepository albumRepository;
	
	@Autowired
	public AlbumServices(AlbumRepository albumRepository) {
		this.albumRepository = albumRepository;
	}
	
	//create
	public boolean addAlbum(Album album) {
		boolean result = true;
		try {
			albumRepository.save(album);
		} catch (Exception e) {
			result = false;
		}
		
		return result;
	}
	
	public void addAlbumByAlbumName(String albumName) {
		// Add code here
		if (albumName != null) {
			albumRepository.save(albumName);
		}
		// add code here
	}
	
	//read
	public List<Album> getAllAlbums() {
		return albumRepository.findAll();
	}
	
	//read - look at all photos in an album
//	public List<Photo> getAllPhotos() {
//		return albumRepository.findAll()
//	}
//	
		
	
	//update
	
	//delete
	public void deleteAlbumByAlbumName(String albumName) {
		albumRepository.deleteByAlbumName(albumName);
	}
	
	
	public void saveAlbum(Album album) {
		albumRepository.save(album);
	}
	
	public Album getAlbumByAlbumName(String albumName) {
		return albumRepository.getAlbumByAlbumName(albumName);
	}
	
	
	
	
	
	
	
	//autogenerated by Eclipse
	
	public List<Album> findAll() {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Album> findAll(Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Album> findAllById(Iterable<Integer> ids) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Album> List<S> saveAll(Iterable<S> entities) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void flush() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Album> S saveAndFlush(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void deleteInBatch(Iterable<Album> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAllInBatch() {
		// TODO Auto-generated method stub
		
	}

	
	public Album getOne(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Album> List<S> findAll(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Album> List<S> findAll(Example<S> example, Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Page<Album> findAll(Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Album> S save(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Optional<Album> findById(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public boolean existsById(Integer id) {
		// TODO Auto-generated method stub
		return false;
	}

	
	public long count() {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public void deleteById(Integer id) {
		// TODO Auto-generated method stub
		
	}

	
	public void delete(Album entity) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll(Iterable<? extends Album> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Album> Optional<S> findOne(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Album> Page<S> findAll(Example<S> example, Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Album> long count(Example<S> example) {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public <S extends Album> boolean exists(Example<S> example) {
		// TODO Auto-generated method stub
		return false;
	}

	
	public Album getAlbumByAlbumId(int id) {
		// TODO Auto-generated method stub
		return null;
	}

}
