package com.Photos.amy.albrecht.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;


import com.Photos.amy.albrecht.models.Like;
import com.Photos.amy.albrecht.repo.LikeRepository;

@Service
public class LikeServices {
	private LikeRepository likeRepository;
	
	@Autowired
	public LikeServices(LikeRepository likeRepository) {
		this.likeRepository = likeRepository;
	}
	
	public void saveLike(Like like) {
		likeRepository.save(like);
	}
	
	public Like countByLikeId(Integer likeId) {
		return likeRepository.countByLikeId(likeId);
	}
	
	//autogenerated by Eclipse
	
	
	public List<Like> findAll() {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Like> findAll(Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Like> findAllById(Iterable<Integer> ids) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Like> List<S> saveAll(Iterable<S> entities) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void flush() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Like> S saveAndFlush(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void deleteInBatch(Iterable<Like> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAllInBatch() {
		// TODO Auto-generated method stub
		
	}

	
	public Like getOne(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Like> List<S> findAll(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Like> List<S> findAll(Example<S> example, Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Page<Like> findAll(Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Like> S save(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Optional<Like> findById(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public boolean existsById(Integer id) {
		// TODO Auto-generated method stub
		return false;
	}

	
	public long count() {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public void deleteById(Integer id) {
		// TODO Auto-generated method stub
		
	}

	
	public void delete(Like entity) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll(Iterable<? extends Like> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Like> Optional<S> findOne(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Like> Page<S> findAll(Example<S> example, Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Like> long count(Example<S> example) {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public <S extends Like> boolean exists(Example<S> example) {
		// TODO Auto-generated method stub
		return false;
	}

	

}
