package com.photos.amy.albrecht.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;


import com.photos.amy.albrecht.models.Likes;
import com.photos.amy.albrecht.repo.LikesRepository;

@Service
public class LikesServices {
	private LikesRepository likesRepository;
	
	@Autowired
	public LikesServices(LikesRepository likesRepository) {
		this.likesRepository = likesRepository;
	}
	
	public void saveLike(Likes likes) {
		likesRepository.save(likes);
	}
	
	public Likes countByLikeId(Integer likesId) {
		return likesRepository.countByLikesId(likesId);
	}
	
	//autogenerated by Eclipse
	
	
	public List<Likes> findAll() {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Likes> findAll(Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Likes> findAllById(Iterable<Integer> ids) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Likes> List<S> saveAll(Iterable<S> entities) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void flush() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Likes> S saveAndFlush(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void deleteInBatch(Iterable<Likes> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAllInBatch() {
		// TODO Auto-generated method stub
		
	}

	
	public Likes getOne(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Likes> List<S> findAll(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Likes> List<S> findAll(Example<S> example, Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Page<Likes> findAll(Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Likes> S save(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Optional<Likes> findById(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public boolean existsById(Integer id) {
		// TODO Auto-generated method stub
		return false;
	}

	
	public long count() {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public void deleteById(Integer id) {
		// TODO Auto-generated method stub
		
	}

	
	public void delete(Likes entity) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll(Iterable<? extends Likes> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Likes> Optional<S> findOne(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Likes> Page<S> findAll(Example<S> example, Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Likes> long count(Example<S> example) {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public <S extends Likes> boolean exists(Example<S> example) {
		// TODO Auto-generated method stub
		return false;
	}

	

}
