package com.Photos.amy.albrecht.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import com.Photos.amy.albrecht.models.Tag;
import com.Photos.amy.albrecht.repo.TagRepository;

@Service
public class TagServices {
	private TagRepository tagRepository;
	
	@Autowired
	public TagServices(TagRepository tagRepository) {
		this.tagRepository = tagRepository;
	}
	
	public void saveTag(Tag tag) {
		tagRepository.save(tag);
	}
	
	public Tag findTagByTagName(String tagName) {
		return tagRepository.findTagByTagName(tagName);
	}
	
	//autogenerated by Eclipse

	
	public List<Tag> findAll() {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Tag> findAll(Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public List<Tag> findAllById(Iterable<Integer> ids) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Tag> List<S> saveAll(Iterable<S> entities) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void flush() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Tag> S saveAndFlush(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public void deleteInBatch(Iterable<Tag> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAllInBatch() {
		// TODO Auto-generated method stub
		
	}

	
	public Tag getOne(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Tag> List<S> findAll(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Tag> List<S> findAll(Example<S> example, Sort sort) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Page<Tag> findAll(Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Tag> S save(S entity) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Optional<Tag> findById(Integer id) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public boolean existsById(Integer id) {
		// TODO Auto-generated method stub
		return false;
	}

	
	public long count() {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public void deleteById(Integer id) {
		// TODO Auto-generated method stub
		
	}

	
	public void delete(Tag entity) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll(Iterable<? extends Tag> entities) {
		// TODO Auto-generated method stub
		
	}

	
	public void deleteAll() {
		// TODO Auto-generated method stub
		
	}

	
	public <S extends Tag> Optional<S> findOne(Example<S> example) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Tag> Page<S> findAll(Example<S> example, Pageable pageable) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public <S extends Tag> long count(Example<S> example) {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public <S extends Tag> boolean exists(Example<S> example) {
		// TODO Auto-generated method stub
		return false;
	}

	
	public Tag getTagByTagId(int id) {
		// TODO Auto-generated method stub
		return null;
	}

}
